### ISSUE TITLE
No realease file in ppa (Ubuntu 20.04)

### ISSUE THREAD

**Issue by ripefig** [adgellida/ubunsys#18]
Bottom text.

**Comment by adgellida** [comment]
Hi. today the secondary alpha PPA is here:

ppa:adgellida/test

In future the primary will be:

ppa:adgellida/ubunsys

as usual

But now, due to various reasons the releases are in:

https://www.linux-apps.com/p/1179908/

I'm working to proportionate an appimage like in the past and snap and flatpak after it.

**Comment by adgellida** [comment]
ppa:adgellida/ubunsys now operative
